import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/Header";
import CommonLayout from "@/components/CommonLayout";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <CommonLayout>
          {children}
        </CommonLayout>
      </body>
    </html>
  );
}
